name: $(Year:yy)$(DayOfYear).$(Rev:r)
trigger: [master]
pr: { branches: { include: [master] } }
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build } ] }
pool: { vmImage: windows-2022 }

stages:
- stage: Build
  displayName: Build
  jobs:
  - job:
    displayName: Build
    variables:
    - group: Code Signing

    steps:
    # Some DateTimeOffset conversion tests rely on being in the UK time zone
    # This is extremely sub-optimal, but means the pipeline can run on hosted agents without breaking changes to the code
    - task: PowerShell@2
      displayName: 'Set Time Zone'
      inputs:
        targetType: 'inline'
        script: Set-TimeZone -Id 'GMT Standard Time'
    
    - template: src/build/dotnet/steps/nuget-package.steps.yaml@templates

- stage: Release
  displayName: Release
  jobs: [ { template: src/deployment/nuget/jobs/internal-public-nuget-package.job.yaml@templates } ]
  condition: and(succeeded(), and(not(eq(variables['Build.Reason'], 'PullRequest')), not(eq(variables['Build.Reason'], 'Schedule'))))
