name: $(Year:yy)$(DayOfYear).$(Rev:r)
trigger:
  - master
pr:
  branches:
    include:
      - master
resources:
  repositories:
    - repository: templates
      type: github
      endpoint: shared-github
      name: audaciaconsulting/Audacia.Build

pool:
  vmImage: windows-latest

variables:
  - group: Audacia.Libraries.Dependency-Track

  # Secrets / env
  - name: DT_API_KEY
    value: $(DT-API-KEY)
  - name: DT_API_URL
    value: $(DT-API-URL)
    
  # Template-parameter variables
  - name: systemName
    value: Audacia.Libraries
  - name: envName
    value: dev
  - name: deactivateOld
    value: true

  # Optional parent project
  - name: parentProjectName
    value: 'Audacia - Libraries'
  - name: parentProjectVersion
    value: ''

  # Project paths and settings
  - name: audaciaSpreadsheetsProjectPath
    value: $(System.DefaultWorkingDirectory)/src/Audacia.Spreadsheets/Audacia.Spreadsheets.csproj

  - name: artifactName
    value: 'sbom-files'
  - name: publishArtifact
    value: true
  - name: failOnUploadError
    value: true
  - name: tryDownloadArtifact
    value: true

stages:
  # =========================
  # 1) GENERATE STAGE
  # =========================
  - stage: generate
    displayName: "Generate SBOMs (npm + .NET via CycloneDX)"
    jobs:
      - job: generate_sbom
        displayName: "Generate SBOMs & publish artifact"
        steps:
          # Generate .NET SBOMs
          - template: /src/security/dependency-track/steps/generate-dotnet-sbom.steps.yaml@templates
            parameters:
              dotnetProjects: |
                $(audaciaSpreadsheetsProjectPath)
                $(audaciaSpreadsheetsTestsProjectPath)
              vstsFeed: 'Audacia.Public/AudaciaPublic'
              nugetConfigPath: ''
              publishArtifact: $(publishArtifact)
              artifactName: $(artifactName)

  # =========================
  # 2) UPLOAD STAGE
  # =========================
  - stage: upload
    displayName: "Upload SBOMs to Dependency-Track"
    dependsOn: generate
    jobs:
      - job: upload_sbom
        displayName: "Upload SBOM & Log Summary"
        steps:
          - checkout: none
          - template: /src/security/dependency-track/steps/upload-sbom.steps.yaml@templates
            parameters:
              envName: $(envName)
              additionalTags: $(additionalTags)
              systemName: $(systemName)
              failOnUploadError: ${{ variables.failOnUploadError }}
              parentProjectName: ${{ variables.parentProjectName }}
              parentProjectVersion: ${{ variables.parentProjectVersion }}

  # =========================
  # 3) DEACTIVATE STAGE (run standalone or after upload)
  # =========================
  - stage: deactivate
    displayName: "Deactivate old Dependency-Track project versions"
    dependsOn: upload
    condition: and(succeeded('upload'), eq(variables['deactivateOld'], true))
    jobs:
      - job: deactivate_old_versions
        displayName: "Set non-latest versions to inactive"
        steps:
          - checkout: none
          - template: /src/security/dependency-track/steps/deactivate-nonlatest.steps.yaml@templates
            parameters:
              artifactName: $(artifactName)
              tryDownloadArtifact: ${{ variables.tryDownloadArtifact }}
              parentProjectName: ${{ variables.parentProjectName }}
